# Generated by Django 3.1.2 on 2020-10-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full_name')),
                ('session', models.FloatField()),
                ('extra', models.IntegerField()),
                ('total', models.FloatField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertificate', models.ImageField(height_field=1280, upload_to='upoads/', verbose_name='Sertificate', width_field=720)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full_name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('point', models.IntegerField()),
                ('description', models.TextField(verbose_name='Description')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating')),
            ],
        ),
    ]
