# Generated by Django 3.1.2 on 2020-10-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_user', models.CharField(default='admin', max_length=255, verbose_name='User')),
                ('excel_file', models.FileField(upload_to='media/excel', verbose_name='ExelFile')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_key', models.CharField(max_length=255, verbose_name='InviteKey')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full_name')),
                ('group', models.CharField(max_length=10, verbose_name='Group')),
                ('session', models.FloatField()),
                ('extra', models.IntegerField()),
                ('total', models.FloatField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('point', models.IntegerField()),
                ('description', models.TextField(verbose_name='Description')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='media/certificate', verbose_name='CertificateFile')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('uploaded_by_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating')),
            ],
        ),
    ]
