# Generated by Django 3.1.2 on 2020-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_key', models.CharField(max_length=255, verbose_name='InviteKey')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExtraPoints',
            new_name='ExtraPoint',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
