# Generated by Django 4.0.6 on 2022-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(upload_to='certificate', verbose_name='CertificateFile'),
        ),
        migrations.AlterField(
            model_name='exelfile',
            name='excel_file',
            field=models.FileField(upload_to='excel', verbose_name='ExcelFile'),
        ),
        migrations.AlterField(
            model_name='extrapoint',
            name='certificate',
            field=models.FileField(upload_to='certificate', verbose_name='Certificate'),
        ),
    ]
